#!/usr/bin/env bash
# Kills the 7-highlander process with the SIGKILL signal.

# The following line disables the shellcheck warning for this specific command.
# shellcheck disable=SC2009
kill -9 "$(ps -ef | grep '[h]ighlander' | awk '{print $2}')"
